# fly.toml app configuration file generated for backend-app-4yrx0q on 2024-11-05T03:55:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-app-4yrx0q'
primary_region = 'qro'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
